{% set name = "flit-scm" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flit_scm-{{ version }}.tar.gz
  sha256: fd0c704375b4424152caced0584cebe4131ccdc236a239dd1a055a80ee935f70

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - flit-core >=3.5.0,<4
    - pip
    - setuptools_scm >=6.4.2,<7
    - tomli
  run:
    - python >=3.6
    - flit-core >=3.5.0,<4
    - setuptools_scm >=6.4.2,<7
    - tomli
test:
  imports:
    - flit_scm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/WillDaSilva/flit_scm
  summary: |
    A PEP 518 build backend that uses setuptools_scm to generate a version file
    from your version control system, then flit_core to build the package.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://gitlab.com/WillDaSilva/flit_scm
  doc_url: https://gitlab.com/WillDaSilva/flit_scm

extra:
  recipe-maintainers:
    - xylar
    - WillDaSilva
